version: "3.9"

services:
  bot:
    image: andreygolovin5/telegrambot:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    environment:
      API_TOKEN: $API_TOKEN
      ADMIN_ID: $ADMIN_ID
      ACCESS_KEY: $ACCESS_KEY
    command: >
      sh -c "python bot/bot.py"