"""Добавление поля is_blocked

Revision ID: 5452124ac936
Revises: 0c8b0115bd08
Create Date: 2024-08-23 22:57:12.758840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5452124ac936'
down_revision: Union[str, None] = '0c8b0115bd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocked_users', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocked_users', 'is_blocked')
    # ### end Alembic commands ###
